/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ca-central-1",
    "aws_cognito_identity_pool_id": "ca-central-1:a3913836-52b9-4b94-b965-99d9b233bd22",
    "aws_cognito_region": "ca-central-1",
    "aws_user_pools_id": "ca-central-1_G2QHaoMeR",
    "aws_user_pools_web_client_id": "7e2qlcumgn0jlcj458uoat4rc1",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://o742y4jlibee5gygioavhdbw34.appsync-api.ca-central-1.amazonaws.com/graphql",
    "aws_appsync_region": "ca-central-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-noinrqsiy5aj5bb4bttbvq7f44",
    "aws_user_files_s3_bucket": "amplifyappec7aae3e9868476e802415e46af95679213516-staging",
    "aws_user_files_s3_bucket_region": "ca-central-1"
};


export default awsmobile;
